### ISSUE TITLE
Maps are not displayed when viewing the restaurant/directions page

### ISSUE THREAD

**Issue by anna-averianova** [SEP007/lmvc-patat#36]
When viewing a page of a restaurant, there is no map displayed. Same happens if you go to the map page (by clicking on invisible map at the restaurant page).

**Comment by tdeekens** [comment]
Cannot reproduce on OS X Mavericks with one of the following
- Chrome 30
- Chrome Canary 33
- Safari 7
- Firefox 24

**Comment by tdeekens** [comment]
Closed as being @anna-averianova Firefox being a jerk.
