### ISSUE TITLE
Get the id of currently logged in customer

### ISSUE THREAD

**Issue by anna-averianova** [SEP007/lmvc-patat#49]
To get an id of the currently logged in customer (not a restaurant!) one needs to do this:

$CustomerModel = new \models\Customers();
$userid = Security::get()->currentUser()->id;
$custid = $CustomerModel->getByUserId($userid)->id;

Since it is used in many places, it would be nice to move somewhere and refactor the remains.

**Comment by chriskoch** [comment]
in a controller inherited from SecureController you can use self::$currentUser->username if @tdeekens followed the given interface.

**Comment by chriskoch** [comment]
All in one...

``` php
$custid = Customers::findByUserId(self::$currentUser->id)->one()->id;
```

… should do it. I'm not sure wether username or id is the primary key.

**Comment by tdeekens** [comment]
Yip jip. I follow the interfaces. Somebody didn't read the code.

The id is in `self::$currentUser->id`. Moreover, the whole user's object properties can be also accessed by name as the `Scandio\lmvc\modules\security\user\User` implements `__get($name)`. Thereby calling `Security::get()->currentUser()->email` gives you an email or `Security::get()->currentUser()->fullname` a full name.
