### ISSUE TITLE
Error after a new restaurant account has been displayed

### ISSUE THREAD

**Issue by danidanone17** [SEP007/lmvc-patat#60]
After creating a new restaurant account, the following error message was displayed:

Invalid argument supplied for foreach() in /www/htdocs/v080275/sep007/composer/scandio/lmvc-modules/lib/Scandio/lmvc/modules/form/AbstractForm.php on line 61

Cannot modify header information - headers already sent by (output started at /www/htdocs/v080275/sep007/composer/scandio/lmvc-modules/lib/Scandio/lmvc/modules/form/AbstractForm.php:61) in /www/htdocs/v080275/sep007/composer/scandio/lmvc/lib/Scandio/lmvc/Controller.php on line 70

Restaurant account data was:
Username: karlsson
Password: karlsson
Email: guswhokwda[at]student.gu.se

Name: Kalssons Garage
Address: Linnegatan 54, 41308 Göteborg, Sweden

**Comment by anna-averianova** [comment]
@anna-averianova has nothing to do with lmvc-modules.

I get a warning about "Invalid argument supplied..." but not the second part.

**Comment by danidanone17** [comment]
@anna-averianova I tried to reproduce the error on the live server. It does not appear any more. So, I consider the bug as fixed and suggest to close it.

**Comment by tdeekens** [comment]
I am a bit hesitant with bugs these days - provoking slackers they are.
Anyhow, I can't see a reason for this bug to occur. Headers can be set using PHP and can't be modified after anything has been outputted - makes sense to my silly brain. Still, the form don't mess much with headers to my understanding. Somehow the controller and the abstract form got into a fight one wanting to set 'em headers too late. 

I've never seen this bug before and I've been refactoring the form-module a bit in my latest story, maybe that even silently solved the issue. I vote for closing and Anya getting a coffee when the bug reoccurs.

Everybody in favor?

:+1:
