### ISSUE TITLE
Mandatory text area is still colored in pink

### ISSUE THREAD

**Issue by danidanone17** [SEP007/lmvc-patat#90]
E.g. in menu edit view, the description text area is colored in pink. It has to be adapted to the color of other mandatory controls.

**Comment by konstantinos-chronis** [comment]
This his me. I forgot to change the CSS for this. I did it only for the other fields

**Comment by konstantinos-chronis** [comment]
This is fixed here: https://github.com/SEP007/lmvc-patat/pull/86
